using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
 * Represents settings that are loaded in on startup. Useful for dynamically loading offsets, other settings.
 * Application-specific, it lives in the Datapath
 * These are initially generated by the current -settings- on build, nd extracted from a text file on startup.
 * 
 * @author
 * max@senseglove.com
 */

public class SG_ConfigSettings
{
    public const string filename = "senseglove.ini";

    public static string GetFileLocation()
    {
        return System.IO.Path.Combine(Application.dataPath, filename);
    }


    //public static void GenerateFromSettings(out string jsonContent)
    //{

    //}
    
    public static void UpdateSettings()
    {
        //If INI exists
        //Load
        //
    }
}
